language: python
python:
  - 3.7
before_install:
  - python --version
  - pip install -U pip
  - pip install -U pipenv
install:
  - pipenv install --dev
  - pipenv shell
script: pytest
after_success:
  - codecov
